FROM debian:stable-slim
LABEL platform="linux/amd64"

# install tools
RUN apt-get update
RUN apt-get install -y git curl nano openssh-server wget openjdk-11-jre

# install jenkins
RUN wget https://get.jenkins.io/war-stable/2.387.3/jenkins.war

# CMD [ "jenkins" ]
CMD ["java" "-Dhudson.model.DirectoryBrowserSupport.CSP" "-Dallow-scripts" "-jar jenkins.war"]