# call image
FROM debian:stable-slim

LABEL platform="linux/amd64"

# install required packages (curl, jdk, git, python, fontconfig)
RUN apt-get update
RUN apt-get install -y curl git python3-pip imagemagick openjdk-11-jre fontconfig wget

# install python library
RUN pip3 install robotframework==5.0 robotframework-appiumlibrary==1.6

# install jenkins
RUN wget https://get.jenkins.io/war-stable/2.387.3/jenkins.war

# CMD [ "jenkins" ]
CMD [ "java", "-Dhudson.model.DirectoryBrowserSupport.CSP", "-jar", "jenkins.war" ]
