FROM debian:stable-slim
LABEL platform="linux/amd64"

# install tools
RUN apt-get update
RUN apt-get install -y git curl openjdk-11-jre openssh-server

# install jenkins
RUN curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null
RUN echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | tee /etc/apt/sources.list.d/jenkins.list > /dev/null
RUN apt-get update
RUN apt-get install -y jenkins

CMD [ "jenkins" ]
