FROM debian:stable-slim
LABEL platform="linux/amd64"

# install required packages (curl, jdk, git, python, fontconfig, nodejs)
RUN apt-get update
RUN apt-get install -y git curl python3-pip openjdk-11-jre wget nano
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get install -y nodejs
RUN npx --yes playwright install-deps

# install python library
ADD requirements.txt requirements.txt
RUN pip3 install -r requirements.txt
RUN rfbrowser init

# remove requirements.txt file from docker
RUN rm requirements.txt

# install jenkins
RUN wget https://get.jenkins.io/war-stable/2.387.3/jenkins.war

# CMD [ "jenkins" ]
CMD [ "java", "-Dhudson.model.DirectoryBrowserSupport.CSP", "-jar", "jenkins.war" ]
